version: '3'

services:
  dev:
    container_name: knowde_front_dev
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd knowde_front && yarn install && yarn start --reload'
    ports:
      - '3000:3000'
    tty: true
